# Generated by Django 4.1.4 on 2024-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_is_customer_user_cats_user_is_company_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactdetails',
            constraint=models.UniqueConstraint(fields=('user', 'mobile'), name='unique_contact'),
        ),
    ]
