# Generated by Django 4.1.4 on 2024-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactdetails_unique_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
